homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/', views.film, name='film'),
    path('story1/',views.index_story1, name='index_story1')
]

story_5/urls.py
from django.urls import path
from . import views
from django.test import Client

app_name = 'story_5'

urlpatterns = [
    path('', views.index_story5, name='index'),
    path('list/', views.MataKuliah_list_view, name='MataKuliah_list_view'),
    path('<int:id>/hapus/', views.MataKuliah_hapus_view, name='MataKuliah_hapus_view'),
    path('tambah/', views.MataKuliah_tambah_view, name='MataKuliah_tambah_view'),
    path('<int:id>/detail/', views.MataKuliah_detail_view, name='MataKuliah_detail_view')
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.kegiatan_view, name='kegiatan_view'),
    path('tambah/', views.Kegiatan_tambah, name='Kegiatan_tambah'),
    path('tambahpeserta/<int:id>/', views.Peserta_tambah, name='Peserta_tambah'),
    
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name='index'),

]

storyppw/storyppw/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage_story1.views import index_story1
from story_5.views import (
    MataKuliah_tambah_view, 
    index_story5, 
    MataKuliah_hapus_view,
    MataKuliah_list_view,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('homepage_story1.urls')),
    path('story5/', include('story_5.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
   
]

story_7/models.py
from django.db import models

# Create your models here.

story_7/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'indexsatu.html')

story_7/templates/base_7.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700;900&display=swap" rel="stylesheet">
    {% block meta %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand text-white" href="#">After UTS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon bg-white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:index' %}">Homepage <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story_5:index' %}">Story 5</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story_6:kegiatan_view' %}">Story 6</a>
            </li>
        </ul>
    </div>
</nav>
<div class="base-kategori">
    <div class="foto-tulisan-foto d-flex justify-content-center justify-content-sm-center
        justify-content-md-center justify-content-lg-center justify-content-xl-center">
        <div class="foto-1 d-flex container-fluid">
            <img src="{% static 'building_3.svg' %}" alt="halo" class="align-self-end align-self-sm-end align-self-md-end
            align-self-lg-end align-self-xl-end">
        </div>
        <div class="kategori-search d-flex flex-column align-items-center align-items-sm-center 
          align-items-md-center align-items-lg-center align-items-xl-center justify-content-center 
          justify-content-sm-center justify-content-md-center justify-content-lg-center 
          justify-content-xl-center">
            {% block headercontent %}
            {% endblock %}
        </div>
        <div class="foto-2 container-fluid d-flex justify-content-center justify-content-sm-center 
          justify-content-md-center justify-content-lg-center justify-content-xl-center">
            <img src="{% static 'building_2.svg' %}" alt="halo" class="align-self-end align-self-sm-end align-self-md-end
            align-self-lg-end align-self-xl-end">
        </div>
    </div>
</div>
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
</body>
<footer>
<br><br><br><br><br>
<div class="footer d-flex flex-column align-items-center align-items-sm-center align-items-md-center
      align-items-lg-center align-items-xl-center">
      <br>
      <div class="text-footer" style="font-size: 25px;">“Without requirements or design, programming is just the art of adding bugs to an empty text file.”</div>
      <div class="text-footer" style="font-size: 25px;">- Louis Srygley -</div>
      
    
    
</div>
</footer>
</html> 

story_7/templates/index_2.html
{% extends 'base_7.html' %}
{% block meta %}
{% load static %}
<title>Landing Page</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/landingPage.css' %}">
{% endblock %}
{% block headercontent %}
<span style="font-size: 50px; line-height: normal;">Story 7</span>
<br>

{% endblock %}
{% block content %}
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

<br><br>

<!-- accordion (start) -->
<div class="accordion">
    <!-- accordion section 1 -->
    <h1 id="accordionhead_1">Heading1  <a href="#" class="reorder-up">Up</a>
        <a href="#" class="reorder-down">Down</a></h1>
        
    <div id="accordioncontent_1" class="accordion-content">
        Content 1
    </div>

    <!-- accordion section 2 -->
    <h1 id="accordionhead_2">Heading2</h1>
    <div id="accordioncontent_2" class="accordion-content">
        Content 2
    </div>

    <!-- accordion section 3 -->
    <h1 id="accordionhead_3">Heading3</h1>
    <div id="accordioncontent_3" class="accordion-content">
        Content 3
    </div>

    <!-- accordion section 4 -->
    <h1 id="accordionhead_4">Heading4</h1>
    <div id="accordioncontent_4" class="accordion-content">
        Content 4
    </div>
</div>
<!-- accordion (end) -->




<script>
    $(document).ready(function(){
        $(".accordion h1").click(function(){
    var id = this.id; 


    $(".accordion-content").each(function(){

        if($("#"+id).next()[0].id != this.id){
            $(this).slideUp("slow");
        }

    });

    $(this).next().toggle("slow");  
});
});

</script>

{% endblock %}

story_7/templates/indexsatu.html
{% extends 'base_7.html' %}
{% block meta %}
<!-- {% load static %} -->
<title>Landing Page</title>
<link rel="icon" href="/static/images/smile.png">
<link rel="stylesheet" type="text/css" href="{% static 'css/landingPage.css' %}">
{% endblock %}
{% block headercontent %}
<span style="font-size: 60px; line-height: normal;">Story 7</span>
<br>

{% endblock %}
{% block content %}
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

<br><br>

<div class="wrapper">
    <div class="container p-5" style="background-color: #00AA13; border-radius: 15px;">


        <div class="ada">
            <button class="accordion text-footer">
                
                <a class="reorder-down">&#x25BC;</a>Kesibukan
                <a class="reorder-up">&#x25B2;</a>
            </button>
            <div id="accordioncontent_1" class="accordion-content">
                <li> Sibuk Kuliah (Semester 3, 22 SKS)</li>
                <li>COMPFEST Academy</li>
            </div>
        </div>


        <div class="ada">
            <button class="accordion text-footer">
                <a class="reorder-down">&#x25BC;</a>Pengalaman
                <a class="reorder-up">&#x25B2;</a>
            </button>
            <div id="accordioncontent_2" class="accordion-content">
                <li>PJ Kreatif Open House Fasilkom </li>
                <li>PJ Dokumentasi PMB Fasilkom </li>
                <li>Staf Event Perak Fasilkom </li>
                <li>Ketua FMA 2019 Fasilkom </li>
            </div>
        </div>

        <div class="ada">
            <button class="accordion text-footer">
                <a class="reorder-down">&#x25BC;</a>Prestasi
                <a class="reorder-up">&#x25B2;</a>
            </button>
            <div id="accordioncontent_3" class="accordion-content">
                <li> Juara lomba short movie gitu pernah</li>
                <li>Juara lomba digital poster gitu pernah</li>
                <li>Juara MTK juga pernah tapi SD :(</li>
                <li>SMA olim komputer cuma sampe osk abisnya males</li>
                <li>Startup gua kepilih masuk Incubator gitu bro, keren ga</li>
                <li>Doain nanti semester >3 bisa ikut lomba2 lagi</li>
            </div>
        </div>

        <div class="ada">
            <button class="accordion text-footer">
                <a class="reorder-down">&#x25BC;</a>Target
                <a class="reorder-up">&#x25B2;</a>
            </button>
            <div id="accordioncontent_4" class="accordion-content">
                <li>Akademis Semester 3 dan seterusnya bisa stabil dan naik</li>
                <li>Academy COMPFEST lancar jaya no chaos</li>
                <li>Liburan bisa magang di weekdays</li>
                <li>Mau jadi asdos pelajaran SI, hehe</li>
            </div>
        </div>
    </div>
</div>

<br><br>
<script>
    $(document).ready(function () {
        $(".accordion-content").hide();
        $(".accordion").click(function () {
            var id = this.id;   /* getting heading id */
            /* looping through all elements which have class .accordion-content */
            $(this).next().toggle("slow");  /* Selecting div after h1 */
        });
    });

    $(".reorder-up").click(function () {
        var $current = $(this).closest('.ada')
        var $previous = $current.prev('.ada');
        if ($previous.length !== 0) {
            $current.insertBefore($previous).delay(10000)  
        }
        return false;
    });

    $(".reorder-down").click(function () {
        var $current = $(this).closest('.ada')
        var $next = $current.next('.ada');
        if ($next.length !== 0) {
            $current.insertAfter($next).delay(10000);
        }
        return false;
    });


</script>




{% endblock %}