homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/', views.film, name='film'),
    path('story1/',views.index_story1, name='index_story1')
]

story_5/urls.py
from django.urls import path
from . import views
from django.test import Client

app_name = 'story_5'

urlpatterns = [
    path('', views.index_story5, name='index'),
    path('list/', views.MataKuliah_list_view, name='MataKuliah_list_view'),
    path('<int:id>/hapus/', views.MataKuliah_hapus_view, name='MataKuliah_hapus_view'),
    path('tambah/', views.MataKuliah_tambah_view, name='MataKuliah_tambah_view'),
    path('<int:id>/detail/', views.MataKuliah_detail_view, name='MataKuliah_detail_view')
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.kegiatan_view, name='kegiatan_view'),
    path('tambah/', views.Kegiatan_tambah, name='Kegiatan_tambah'),
    path('tambahpeserta/<int:id>/', views.Peserta_tambah, name='Peserta_tambah'),
    
]

storyppw/storyppw/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage_story1.views import index_story1
from story_5.views import (
    MataKuliah_tambah_view, 
    index_story5, 
    MataKuliah_hapus_view,
    MataKuliah_list_view,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('homepage_story1.urls')),
    path('story5/', include('story_5.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
   
]

story_6/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=100)
    
    def __str__(self):
        return self.namaKegiatan

class Peserta(models.Model):
    namaPeserta = models.CharField(max_length=100)
    daftarKegiatan = models.ForeignKey(Kegiatan, null=True, on_delete= models.CASCADE)

    def __str__(self):
        return self.namaPeserta

story_6/forms.py
from django import forms
from .models import Kegiatan, Peserta


class KegiatanForms(forms.ModelForm):
    namaKegiatan = forms.CharField(label='Nama Kegiatan', 
                    widget=forms.TextInput(attrs={"placeholder": "Kegiatan"}), )
   

    class Meta:
        model = Kegiatan
        fields = [
            'namaKegiatan',
            
        ]
    
class PesertaForms(forms.ModelForm):
    namaPeserta = forms.CharField(label='Nama Anda', 
                    widget=forms.TextInput(attrs={"placeholder": "Masukkan Nama"}), )
   

    class Meta:
        model = Peserta
        fields = [
            'namaPeserta',
            
        ]
    

story_6/views.py
from django.shortcuts import render, get_object_or_404, render, redirect
from .models import Kegiatan, Peserta
from .forms import KegiatanForms, PesertaForms

# from .forms import MataKuliahForms #GANTIIIII
from django.contrib import messages
# Create your views here.

def kegiatan_view(request):
    queryset = Kegiatan.objects.all()
    kumpulanPeserta = Peserta.objects.all()
    return render(request, "kegiatan_view.html", {"kumpulanPeserta":kumpulanPeserta, "semuaKegiatan":queryset})


def Kegiatan_tambah(request):
    
    form = KegiatanForms(request.POST or None)
    if form.is_valid(): #validator
        form.save()
    context = {
        'form' : form
    }
    return render(request, "kegiatan_form.html", context)

def Peserta_tambah(request, id=0):
    if request.method == "POST":
        form = PesertaForms(request.POST or None)
        if form.is_valid():
            pendaftarValid = Peserta(daftarKegiatan=Kegiatan.objects.get(pk=id), namaPeserta=form.data['namaPeserta'])
            pendaftarValid.save()
        return redirect('/story6/')
    form = PesertaForms()
    return render(request, "peserta_form.html", {'peserta': form})

story_6/templates/base_story6.html
{%load static%}

<head>
<html lang="en-US" style="scroll-behavior: smooth;">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Rezaldy's Story</title>
  <link rel="icon" href="/static/images/smile.png">
  <meta name="description" content="Web yang berisi tentang Zaldy dan Story PPW-nya">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat:400,700,200' %}" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  
  <!-- <link href="css/aos.css" rel="stylesheet"> -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href=" {% static 'styles/main.css' %}" rel="stylesheet">

</head>

<header>
    <div class="profile-page sidebar-collapse">
        <nav class="navbar navbar-expand-lg fixed-top" color-on-scroll="400" ;">
        <div class="container style=">
            {%block navbar%}
            {% endblock %}
        </div>
        </nav>
    </div>
</header>

<div style="background-color: rgb(35, 168, 86);"></div>
<br><br><br><br>
{% block content %}
{% endblock %}
</div>

story_6/templates/kegiatan_form.html
<!DOCTYPE html>
{% extends 'base_story6.html' %}

{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}

{% block content %}


<form method="POST" style="margin: 10px;">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p}}
        <input class="btn" type="submit" value="Save" />
    </div>
</form> <br><br>
<a class="btn btn-primary btn-dark" href="{% url 'story_6:kegiatan_view' %}" role="button">Lihat Daftar Kegiatan</a>

{% endblock %}

story_6/templates/kegiatan_view.html
<!DOCTYPE html>
{% extends 'base_story6.html' %}

{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}

{% block content %}



<div class="container">
    <a class="btn btn-dark btn-lg btn-block" style="font-size: large; color: white;
     background-color: rgb(19, 20, 20) ; width: 15rem; justify-content: center; margin-bottom: 30px;"
        href="{% url 'story_6:Kegiatan_tambah' %}" role="button">+ Tambah Kegiatan</a>
    <div class="row">

    
    {% for keg in  semuaKegiatan %}
        <div class="card bg-dark text-white"
            style="width: 20rem; box-shadow: 2px 15px 15px 0 rgba(0,0,0,0.2); margin: 20px; max-width: 100%; align-content: center; border-radius: 10px ;">
            <div class="card-header"> Kegiatan {{keg.id}}</div>
            <div class="card-body">
                <div class="card-title" style="font-size:x-large;">{{keg.namaKegiatan}}</div>
               
                <h6>
                Peserta:
                </h6>
                
                {% for instance in kumpulanPeserta %}
                {% if instance.daftarKegiatan == keg %}
                <div style="color: rgb(45, 167, 45);"> {{ instance.namaPeserta }}</div>
                
                {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer">
                <form action="" method="POST"
                {% csrf_token %}
                <a id="tambah" href="{% url 'story_6:Peserta_tambah' id=keg.id %}" class="btn" >Klik Untuk Mendaftar</a>
            </div>
        </div>
        {% endfor %}

    </div>
</div>


{% endblock %}

story_6/templates/peserta_form.html
<!DOCTYPE html>
{% extends 'base_story6.html' %}

{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}

{% block content %}

<form method="POST" style="margin: 10px;">
    {% csrf_token %}
    <div class="form-group">
        {{ peserta }}
        <input class="btn" type="submit" value="Save" />
    </div>
</form> <br><br>
<a class="btn btn-primary btn-dark" href="{% url 'story_6:kegiatan_view' %}" role="button">Lihat Daftar Kegiatan</a>


{% endblock %}