homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/', views.film, name='film'),
    path('story1/',views.index_story1, name='index_story1')
]

story_5/urls.py
from django.urls import path
from . import views
from django.test import Client

app_name = 'story_5'

urlpatterns = [
    path('', views.index_story5, name='index'),
    path('list/', views.MataKuliah_list_view, name='MataKuliah_list_view'),
    path('<int:id>/hapus/', views.MataKuliah_hapus_view, name='MataKuliah_hapus_view'),
    path('tambah/', views.MataKuliah_tambah_view, name='MataKuliah_tambah_view'),
    path('<int:id>/detail/', views.MataKuliah_detail_view, name='MataKuliah_detail_view')
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.kegiatan_view, name='kegiatan_view'),
    path('tambah/', views.Kegiatan_tambah, name='Kegiatan_tambah'),
    path('tambahpeserta/<int:id>/', views.Peserta_tambah, name='Peserta_tambah'),
    
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name='index'),

]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.fungsi_suatu_url, name='fungsi_suatu_url'),
    path('data/',views.fungsi_data, name='fungsi_data'),
]

storyppw/storyppw/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage_story1.views import index_story1
from story_5.views import (
    MataKuliah_tambah_view, 
    index_story5, 
    MataKuliah_hapus_view,
    MataKuliah_list_view,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('homepage_story1.urls')),
    path('story5/', include('story_5.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
   
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def film(request):
    return render(request, 'film_rec.html')

def index_story1(request):
    return render(request, 'index_story1.html')

homepage/templates/base.html
{%load static%}

<head>
<html lang="en-US" style="scroll-behavior: smooth;">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Rezaldy's Story</title>
  <link rel="icon" href="/static/images/smile.png">
  <meta name="description" content="Web yang berisi tentang Zaldy dan Story PPW-nya">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat:400,700,200' %}" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- <link href="css/aos.css" rel="stylesheet"> -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href=" {% static 'styles/main.css' %}" rel="stylesheet">

</head>

<header>
    <div class="profile-page sidebar-collapse">
        <nav class="navbar navbar-expand-lg fixed-top" color-on-scroll="400" ;">
        <div class="container">
            {%block navbar%}
            
            {% endblock %}
        </div>
        </nav>
    </div>
</header>

{% block content %}
{% endblock %}



<footer class="footer" style="background-color: #5511A7;">

    <div class="container text-center"><a class="cc-facebook btn btn-link" id="logo-footer"
        href="https://www.facebook.com/Reza38"><i class="fa fa-facebook fa-2x " id="logo-footer"
          aria-hidden="true"></i></a><a class="cc-twitter btn btn-link " id="logo-footer"
        href="https://twitter.com/ChrisEvans"><i class="fa fa-twitter fa-2x " aria-hidden="true"></i></a><a
        class="cc-google-plus btn btn-link" id="logo-footer" href="https://myaccount.google.com" /><i
        class="fa fa-google-plus fa-2x" aria-hidden="true"></i></a><a class="cc-instagram btn btn-link" id="logo-footer"
        href="https://www.instagram.com/rezaldyahm/"><i class="fa fa-instagram fa-2x " id="logo-footer"
          aria-hidden="true"></i></a></div>

    <div class="h4 title text-center">Rezaldy Maulana</div>

    <div class="text-center text-muted">
      <p>&copy; Creative CV. All rights reserved.<br>Design by - <a class="credit" href="#" target="_blank">Template
          Flip</a> <br>Customized by - <a class="credit" href="https://instagram.com/rezaldyahm" target="_blank">Rezaldy
          Maulana</a> <br><br><br></p>
    </div>
  </footer>

homepage/templates/film_rec.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}




{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}



{% block content %}

<div class="content">
    <br><br><br>
    <div class="container">
        <div class="proyek"></div>
        <hr style="height:4px;width: 100%;color:gray;background-color: #2c063c">
        <div class="h4 mt-0 title" style="text-align: center; padding-top: 20px;">Film Recommendation</div>
        <br>
        <div class="card mb-3" style="max-width: 100%; align-content: center; border-radius: 20px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="/static/images/avatar.jpg" class="card-img" alt="..."
                        style="border-radius: 30px; padding: 20px;">

                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Avatar</h5>
                        <p class="card-text text-justify">On the lush alien world of Pandora live the Na'vi, beings who
                            appear primitive but are highly evolved.
                            Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars, must
                            link to human minds to allow for free movement on Pandora.
                            Jake Sully (Sam Worthington), a paralyzed former Marine, becomes mobile again through one
                            such Avatar and falls in love with a Na'vi woman (Zoe Saldana).
                            As a bond with her grows, he is drawn into a battle for the survival of her world.</p>
                        <p class="card-text"><small class="text-muted">Adventure | Sci-fi | Action | War
                        </p>
                    </div>
                </div>
            </div>
        </div> <br><br>
        <div class="card mb-3" style="max-width: 100%; align-content: center; border-radius: 20px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="/static/images/fg.jpeg" class="card-img" alt="..."
                        style="border-radius: 30px; padding: 20px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 25px;">Forrest Gump</h5>
                        <p class="card-text text-justify" style="font-size: 16px;">Slow-witted Forrest Gump (Tom Hanks)
                            has never thought of himself as disadvantaged,
                            and thanks to his supportive mother (Sally Field), he leads anything but a restricted life.
                            Whether dominating on the gridiron as a college
                            football star, fighting in Vietnam or captaining a shrimp boat, Forrest inspires people with
                            his childlike optimism. But one person Forrest
                            cares about most may be the most difficult to save -- his childhood love, the sweet but
                            troubled Jenny (Robin Wright).</p>
                        <p class="card-text"><small class="text-muted">Romance | Drama | Motivational | Comedy</small>
                        </p>
                    </div>
                </div>
            </div>
        </div> <br><br>
        <div class="card mb-3" style="max-width: 100%; align-content: center;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="/static/images/ib.jpg" class="card-img" alt="..." style="border-radius: 30px; padding: 20px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 25px;">Inglourious Basterds</h5>
                        <p class="card-text text-justify" style="font-size: 16px;">It is the first year of Germany's
                            occupation of France. Allied officer Lt. Aldo Raine (Brad Pitt)
                            assembles a team of Jewish soldiers to commit violent acts of retribution against the Nazis,
                            including the taking of their scalps. He and his men join
                            forces with Bridget von Hammersmark, a German actress and undercover agent, to bring down
                            the leaders of the Third Reich. Their fates converge with theater
                            owner Shosanna Dreyfus, who seeks to avenge the Nazis' execution of her family.</p>
                        <p class="card-text"><small class="text-muted">War | Action | Drama </small>
                        </p>
                    </div>
                </div>
            </div>
        </div> <br><br>
        <div class="card mb-3" style="max-width: 100%; align-content: center;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="/static/images/ts.jpeg" class="card-img" alt="..."
                        style="border-radius: 30px; padding: 20px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 25px;">The Truman Show</h5>
                        <p class="card-text text-justify" style="font-size: 16px;">He doesn't know it, but everything in
                            Truman Burbank's (Jim Carrey) life is part of a massive TV set.
                            Executive producer Christof (Ed Harris) orchestrates "The Truman Show," a live broadcast of
                            Truman's every move captured by hidden cameras. Cristof tries to
                            control Truman's mind, even removing his true love, Sylvia (Natascha McElhone), from the
                            show and replacing her with Meryl (Laura Linney). As Truman gradually
                            discovers the truth, however, he must decide whether to act on it.
                        </p>
                        <p class="card-text"><small class="text-muted">Comedy | Drama </small>
                        </p>
                    </div>
                </div>
            </div>
        </div> <br><br>

    </div>
    </div>
</div>

{% endblock %}
<!-- 
<footer class="footer" style="background-color: #5511A7;">

    <div class="container text-center"><a class="cc-facebook btn btn-link" id="logo-footer"
            href="https://www.facebook.com/Reza38"><i class="fa fa-facebook fa-2x " id="logo-footer"
                aria-hidden="true"></i></a><a class="cc-twitter btn btn-link " id="logo-footer"
            href="https://twitter.com/ChrisEvans"><i class="fa fa-twitter fa-2x " aria-hidden="true"></i></a><a
            class="cc-google-plus btn btn-link" id="logo-footer" href="https://myaccount.google.com" /><i
            class="fa fa-google-plus fa-2x" aria-hidden="true"></i></a><a class="cc-instagram btn btn-link"
            id="logo-footer" href="https://www.instagram.com/rezaldyahm/"><i class="fa fa-instagram fa-2x "
                id="logo-footer" aria-hidden="true"></i></a></div>

    <div class="h4 title text-center">Rezaldy Maulana</div>

    <div class="text-center text-muted">
        <p>&copy; Creative CV. All rights reserved.<br>Design by - <a class="credit" href="#" target="_blank">Template
                Flip</a> <br>Customized by - <a class="credit" href="https://instagram.com/rezaldyahm"
                target="_blank">Rezaldy
                Maulana</a> <br><br><br><br></p>
    </div>
</footer> -->

</div>

</html>

homepage/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

    {% block navbar %}
      <div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="#" rel="tooltip">Me</a></div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="navbar-nav">
          <li class="nav-item""><a class=" nav-link text-light" href="{% url 'story_6:kegiatan_view' %}">Story 6</a></li>
          <li class="nav-item"><a class="nav-link  text-light" href="{% url 'story_7:index' %}"> Story 7</a></li>
          <li class="nav-item"><a class="nav-link text-light" href="{% url 'story_8:fungsi_suatu_url' %}"> Story 8</a></li>
          <li class="nav-item"><a class="nav-link text-light" href="{% url 'story_5:MataKuliah_list_view' %}"> Matkul</a></li>
      </ul>
      </div>
    {% endblock %}
  {% block content %}
<div class="content" style="scroll-behavior: smooth;">
  <div class="page-content" style="background-color: #5DCAE8;">
    <div class="profile-page" style="margin: 50px 0px 30px 0px;">
      <div class="wrapper">
        <div class="page-header page-header-small">
          <div class="container">
            <div class="content-center">
              <div class="cc-profile-image"><a href="#about"><img src="static/images/zaldy_dokum.png" alt="Image" /></a>
              </div>
              <div class="h4 title" style="color: rgb(232, 232, 232);">Rezaldy Maulana</div>
              <p class="category text-light"> Graphic Designer | Student | Startup Enthusiast</p>
              <!-- <a class="btn btn-primary smooth-scroll mr-2" href="#contact" data-aos="zoom-in" data-aos-anchor="data-aos-anchor">Hire Me</a><a class="btn btn-primary" href="#" data-aos="zoom-in" data-aos-anchor="data-aos-anchor">Download CV</a> -->
            </div>
          </div>
          <div class="section" id="About">
            <div class="container" style="padding-top: 55px;">
              <div class="button-container""><a class="btn btn-default btn-round btn-lg btn-icon"
                  href="https://www.facebook.com/Reza38" rel="tooltip" title="Follow me on Facebook"><i
                    class="fa fa-facebook"></i></a><a class="btn btn-default btn-round btn-lg btn-icon"
                  href="https://twitter.com/ChrisEvans" rel="tooltip" title="I deactivate my twitter :(">
                  <i class="fa fa-twitter"></i></a><a class="btn btn-default btn-round btn-lg btn-icon"
                  href="https://www.google.co.id/" rel="tooltip" title="Follow me on Google+"><i
                    class="fa fa-google-plus"></i></a><a class="btn btn-default btn-round btn-lg btn-icon"
                  href="https://www.instagram.com/rezaldyahm/" rel="tooltip" title="Follow me on Instagram"><i
                    class="fa fa-instagram"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>

  <div class="selection">
    <div class="container">
      <div class="card text-center p-0" style=" border-radius: 20px; background-color:#4E1792; border: none;">
        <div class="card-body" style="border: none; border-radius: 20px; border-color: #2c063c;">
          <h5 class="card-title h4 mt-0 title">Tentang</h5>
          <p class="card-text">Lahir di Jakarta, 28 Mei 2001. Saya sedang mengenyam pendidikan S1 jurusan Sistem
            Informasi,
            Fasilkom di Universitas Indonesia. Saya adalah orang yang sangat antusias dengan segala hal berbau digital
            design
            dan selalu merasa tertantang untuk mengerjakan projek-projek baru yang menyelesaikan masalah pendidikan dan
            sosial.
          </p>
        </div>
      </div>
    </div>
    <br>
    <div class="container">
      <div class="proyek"></div>
      <div class="card p-0" data-aos="fade-up" data-aos-offset="10" style="border: none;">
        <div class="row">
          <div class="col-lg-6 col-md-12" style="padding-bottom: 20px;">
            <div class="card-body" style="background-color: #4E1593; border-radius: 20px;">
              <div class="h4 mt-0 title">Informasi Singkat</div>
              <div class="row">
                <div class="col-sm-4"><strong class="text-uppercase">NPM</strong></div>
                <div class="col-sm-8">:1906299105</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">Hobi</strong></div>
                <div class="col-sm-8">: Sepak Bola, Nonton Film Dokumenter</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">Pendidikan</strong></div>
                <div class="col-sm-8">: Sistem Informasi, Universitas Indonesia</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">Domisili</strong></div>
                <div class="col-sm-8">: Depok</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-12">
            <div class="card-body" style="background-color: rgba(48, 40, 63, 0.2); border-radius: 20px;">
              <div class="h4 mt-0 title">Riwayat Pendidikan</div>
              <div class="row">
                <div class="col-sm-4"><strong class="text-uppercase">SD</strong></div>
                <div class="col-sm-8">: SDIT Nurul Fikri</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">SMP</strong></div>
                <div class="col-sm-8">: SMPIT Nurul Fikri</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">SMA</strong></div>
                <div class="col-sm-8">: SMAN 3 Depok</div>
              </div>
              <div class="row mt-3">
                <div class="col-sm-4"><strong class="text-uppercase">S1</strong></div>
                <div class="col-sm-8" id="Proyek">: Universitas Indonesia</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>

  <br><br>
  <div class="container">
    <div class="proyek"></div>
    <hr style="height:4px;width: 100%;color:gray;background-color: #2c063c">
    <div class="h4 mt-0 title" style="text-align: center; padding-top: 20px;">Proyek</div>
    <div class="card mb-3" style="max-width: 100%; align-content: center; border-radius: 20px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="static/images/proyek2.png" class="card-img" alt="..." style="border-radius: 30px; padding: 20px;">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Belumjadi.com</h5>
            <p class="card-text text-justify">Belumjadi.com merupakan platform forum yang belum jadi. Lorem Ipsum is
              simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
              dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
              survived not only five centuries.
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
              industry's standard dummy text ever
              since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
              book. It has survived not only five centuries.</p>
            <p class="card-text"><small class="text-muted">React.js | Python | Django | HTML | CSS<< /small>
            </p>
          </div>
        </div>
      </div>
    </div> <br><br>
    <div class="card mb-3" style="max-width: 100%; align-content: center; border-radius: 20px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="static/images/proyek2.png" class="card-img" alt="..." style="border-radius: 30px; padding: 20px;">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Sekelas.net</h5>
            <p class="card-text text-justify" style="font-size: 16px;">Belumjadi.com merupakan platform forum yang belum
              jadi. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
              industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
              scrambled it to make a type specimen book. It has survived not only five centuries.
              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
              industry's
              standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it
              to make
              a type specimen book. It has survived not only five centuries.</p>
            <p class="card-text"><small class="text-muted">React.js | Python | Django | HTML | CSS<< /small>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div style="text-align: center;">
      <br>
      <a style="font-size: 20px; color: aliceblue;" href="{% url 'homepage:film' %}"><u>Movie Bucket List</u></a>
      </button>
      <br><br><br>
    </div>
  </div>

</div>



{% endblock%}