homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/', views.film, name='film'),
    path('story1/',views.index_story1, name='index_story1')
]

story_5/urls.py
from django.urls import path
from . import views
from django.test import Client

app_name = 'story_5'

urlpatterns = [
    path('', views.index_story5, name='index'),
    path('list/', views.MataKuliah_list_view, name='MataKuliah_list_view'),
    path('<int:id>/hapus/', views.MataKuliah_hapus_view, name='MataKuliah_hapus_view'),
    path('tambah/', views.MataKuliah_tambah_view, name='MataKuliah_tambah_view'),
    path('<int:id>/detail/', views.MataKuliah_detail_view, name='MataKuliah_detail_view')
]

storyppw/storyppw/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage_story1.views import index_story1
from story_5.views import (
    MataKuliah_tambah_view, 
    index_story5, 
    MataKuliah_hapus_view,
    MataKuliah_list_view,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('homepage_story1.urls')),
    path('story5/', include('story_5.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('story9/', include('story_9.urls')),
   
]

story_5/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse

# Create your models here.
class MataKuliah(models.Model):
    nama = models.CharField(max_length=120)
    dosen = models.CharField(max_length=120)
    jumlahsks = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(6)])
    deskripsi = models.TextField(blank=True, null=True)
    ruangkelas = models.CharField(max_length=120, default='DEFAULT VALUE')
    CHOICES = (('a','Gasal 2019/2020'),
               ('b','Genap 2018/2019'),
               ('c','Gasal 2018/2019'),
               ('d','Genap 2017/2018'),
               ('e','Gasal 2018/2018'),
               ('f','Genap 2016/2017'),
               ('g','Gasal 2016/2017'),)
    semestertahun = models.CharField(max_length = 20, choices = CHOICES, default = '1',)

    def __str__(self):
            return self.nama



    

story_5/forms.py
from django import forms
from .models import MataKuliah

class MataKuliahForms(forms.ModelForm):
    nama = forms.CharField(label='Nama Matkul', 
                    widget=forms.TextInput(attrs={"placeholder": "Mata Kuliah"}), )
    dosen = forms.CharField(label='Nama Dosen', 
                    widget=forms.TextInput(attrs={"placeholder": "Nama Dosen"}))
    ruangkelas = forms.CharField(label='Ruang Kelas', 
                    widget=forms.TextInput(attrs={"placeholder": "Ruang Kelas"}))

    
    class Meta:
        model = MataKuliah
        fields = [
            'nama',
            'dosen',
            'ruangkelas',
            'semestertahun',
            'jumlahsks',
            'deskripsi'
        ]
    

story_5/views.py
from django.shortcuts import get_object_or_404, render, redirect

from .models import MataKuliah
from .forms import MataKuliahForms
from django.contrib import messages
# Create your views here.

def index_story5(request):
    return render(request, 'index_story5.html')

def MataKuliah_tambah_view(request):
    form = MataKuliahForms(request.POST or None)
    if form.is_valid(): #validator
        form.save()
    
    context = {
        'form' : form
    }
    return render(request, "matkul_tambah.html", context)


def MataKuliah_hapus_view(request, id):
    obj = get_object_or_404(MataKuliah, id=id)
    if request.method == "POST":
        # Mengkonfirmasi penghapusan
        obj.delete()
    context = {
        'Object' : obj
    }
    return render(request, "matkul_hapus.html", context)


def MataKuliah_list_view(request):
    queryset = MataKuliah.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, "matkul_list.html", context)


def MataKuliah_detail_view(request, id):
    obj = get_object_or_404(MataKuliah, id=id)
    context = {
        'Object' : obj
    }
    return render(request, 'matkul_detail.html', context)

# Input :
# - Nama Mata Kuliah
# - Dosen Pengajar
# - Jumlah SKS (number integer)
# - Deskripsi
# - Ruang
# - Semester Tahiun

# Fitur :
# - tambah
# - hapus
# - ketika sudah ada maka terupdate, jika belum maka akan tertambah
# - detail mata kuliah

story_5/templates/base_story5.html
{%load static%}

<head>
<html lang="en-US" style="scroll-behavior: smooth;">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Rezaldy's Story</title>
  <link rel="icon" href="/static/images/smile.png">
  <meta name="description" content="Web yang berisi tentang Zaldy dan Story PPW-nya">
  <link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat:400,700,200' %}" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  
  <!-- <link href="css/aos.css" rel="stylesheet"> -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href=" {% static 'styles/main.css' %}" rel="stylesheet">

</head>

<header>
    <div class="profile-page sidebar-collapse">
        <nav class="navbar navbar-expand-lg fixed-top" color-on-scroll="400" ;">
        <div class="container style=">
            {%block navbar%}
            
            {% endblock %}
        </div>
        </nav>
    </div>
</header>

<br><br><br><br>
{% block content %}
{% endblock %}

story_5/templates/matkul_detail.html
<!DOCTYPE html>
{% extends 'base_story5.html' %}

{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}

{% block content %}

<br><br><br><br>
<div class="selection style="background-color: #5DCAE8;">
    <div class="container"">
    <div class="card" style="width: 25rem; height: 25rem">
  <div class="card-body">

    <h5 class="card-title text-dark">{{Object.nama}} </h5><br>
    <h6 class="card-subtitle mb-2 text-dark"> Jumlah SKS :{{Object.jumlahsks}} </h6><br>
    <h6 class="card-subtitle mb-2 text-dark"> Dosen :{{Object.dosen}} </h6><br>
    <h6 class="card-subtitle mb-2 text-dark"> Ruang Kelas :{{Object.ruangkelas}} </h6><br>
    <h6 class="card-subtitle mb-2 text-dark"> Deskripsi: {{Object.deskripsi}} </h6><br><br>
    
  </div>
</div>

<th scope="row">{{instance.nama}}</th>
            <td>{{instance.dosen}}</td>
            <td>{{instance.jumlahsks}}</td>
            <td>{{instance.ruangkelas}}</td><br>
    <a class="btn btn-primary" href="{% url 'story_5:MataKuliah_list_view' %}" role="button">Lihat List Matkul</a>
    </div>
</div>


{% endblock %}

story_5/templates/matkul_hapus.html
<!DOCTYPE html>
{% extends 'base_story5.html' %}

{%block navbar%}
<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'story_5:MataKuliah_list_view' %}"
        rel="tooltip">Back</a>
</div>

{% endblock %}

{% block content%}

<br><br><br><br>
<div class="selection">
    <div class="container">
<form action='.' method='POST'>{% csrf_token %}
    <h1>Apakah kamu YAKIN ingin menghapus matkul "{{ Object.nama }}" ?</h1>
    <br>
    <h1><input type='submit' value='Yes' onclick="location.href='matkul_list.html';"/> <a href="{% url 'story_5:MataKuliah_list_view' %}">   Cancel</a></h1>
</form>
</div></div>
{%endblock%}

 

story_5/templates/matkul_list.html
<!DOCTYPE html>
{% extends 'base_story5.html' %}

{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'homepage:index' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}


{% block content %}

<div class="selection">
    <div class="container">
    <table class="table table-dark table-striped">
        <thead>
            <tr>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Dosen</th>
            <th scope="col">JumlahSKS</th>
            <th scope="col">Ruangan</th>
            <th scope="col">Lihat Detail</th>
            <th scope="col">Hapus</th>
            </tr>
            </thead>
        <tbody>
            {% for instance in  object_list %}
            <tr>
            <th scope="row">{{instance.nama}}</th>
            <td>{{instance.dosen}}</td>
            <td>{{instance.jumlahsks}}</td>
            <td>{{instance.ruangkelas}}</td>
            <td><a id="detail" href="{% url 'story_5:MataKuliah_detail_view' instance.id %}" class="card-link">Lihat</a></td>
            <td><a id="delete" href="{% url 'story_5:MataKuliah_hapus_view' instance.id %}" class="card-link">Hapus</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </div>
<a class="btn btn-primary btn-dark btn-lg btn-block" href="{% url 'story_5:MataKuliah_tambah_view' %}" role="button">Tambah</a>
</div>
{% endblock %}

story_5/templates/matkul_tambah.html
<!DOCTYPE html>
{% extends 'base_story5.html' %}


{%block navbar%}

<div class="navbar-translate navbar-dark"><a class="navbar-brand text-light" href="{% url 'story_5:MataKuliah_list_view' %}"
        rel="tooltip">Back</a>
</div>
{% endblock %}



{% block content %}

<br><br><br><br>
<form method="POST" style="margin: 10px;">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p}}
        <input type="submit" value="Save" />
    </div>
  </form> 
  
<a class="btn btn-primary btn-dark" href="{% url 'story_5:MataKuliah_list_view' %}" role="button">Lihat Daftar Matkul</a>

{% endblock %}